# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d7863151f94dd295eaf125a6bcf33386676b4e73475a55a50eb574a2b3cbc20a8c13071979261d66d76729cd49742e8b725d1e0929eb4b976f72d530c85199e

test:
  secret_key_base: 2963815850e6542bbdefa7981fe9ded6cbc4076ed3ff551c4806f23921c625f54a6484dcbe1c682716c41ae743f6de714c1574421daa53bc91f54e2bab72dd76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 41b5b8148c404a6e59709913ae40a217f089112989ebff7e80a8d6fbbedacad7de1b77b279c0c71b8b50cc0f5c6ae9e8628e3eebe0edd09436bf1cd00a1c0671

# development:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# test:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#   aws_s3_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>  
#   aws_s3_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>